/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SihirbazRouteImport } from './routes/sihirbaz'
import { Route as KosullarRouteImport } from './routes/kosullar'
import { Route as KarsilastirRouteImport } from './routes/karsilastir'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HesabimRouteImport } from './routes/hesabim'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as GizlilikRouteImport } from './routes/gizlilik'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UrunlerIndexRouteImport } from './routes/urunler.index'
import { Route as RehberIndexRouteImport } from './routes/rehber.index'
import { Route as IsimlerIndexRouteImport } from './routes/isimler.index'
import { Route as HamilelikIndexRouteImport } from './routes/hamilelik.index'
import { Route as RehberSlugRouteImport } from './routes/rehber.$slug'
import { Route as IsimlerIsimRouteImport } from './routes/isimler.$isim'
import { Route as HamilelikDonemRouteImport } from './routes/hamilelik.$donem'
import { Route as UrunlerKategoriIndexRouteImport } from './routes/urunler.$kategori.index'
import { Route as UrunlerKategoriSlugRouteImport } from './routes/urunler.$kategori.$slug'

const SihirbazRoute = SihirbazRouteImport.update({
  id: '/sihirbaz',
  path: '/sihirbaz',
  getParentRoute: () => rootRouteImport,
} as any)
const KosullarRoute = KosullarRouteImport.update({
  id: '/kosullar',
  path: '/kosullar',
  getParentRoute: () => rootRouteImport,
} as any)
const KarsilastirRoute = KarsilastirRouteImport.update({
  id: '/karsilastir',
  path: '/karsilastir',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HesabimRoute = HesabimRouteImport.update({
  id: '/hesabim',
  path: '/hesabim',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikRoute = GizlilikRouteImport.update({
  id: '/gizlilik',
  path: '/gizlilik',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UrunlerIndexRoute = UrunlerIndexRouteImport.update({
  id: '/urunler/',
  path: '/urunler/',
  getParentRoute: () => rootRouteImport,
} as any)
const RehberIndexRoute = RehberIndexRouteImport.update({
  id: '/rehber/',
  path: '/rehber/',
  getParentRoute: () => rootRouteImport,
} as any)
const IsimlerIndexRoute = IsimlerIndexRouteImport.update({
  id: '/isimler/',
  path: '/isimler/',
  getParentRoute: () => rootRouteImport,
} as any)
const HamilelikIndexRoute = HamilelikIndexRouteImport.update({
  id: '/hamilelik/',
  path: '/hamilelik/',
  getParentRoute: () => rootRouteImport,
} as any)
const RehberSlugRoute = RehberSlugRouteImport.update({
  id: '/rehber/$slug',
  path: '/rehber/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IsimlerIsimRoute = IsimlerIsimRouteImport.update({
  id: '/isimler/$isim',
  path: '/isimler/$isim',
  getParentRoute: () => rootRouteImport,
} as any)
const HamilelikDonemRoute = HamilelikDonemRouteImport.update({
  id: '/hamilelik/$donem',
  path: '/hamilelik/$donem',
  getParentRoute: () => rootRouteImport,
} as any)
const UrunlerKategoriIndexRoute = UrunlerKategoriIndexRouteImport.update({
  id: '/urunler/$kategori/',
  path: '/urunler/$kategori/',
  getParentRoute: () => rootRouteImport,
} as any)
const UrunlerKategoriSlugRoute = UrunlerKategoriSlugRouteImport.update({
  id: '/urunler/$kategori/$slug',
  path: '/urunler/$kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gizlilik': typeof GizlilikRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hesabim': typeof HesabimRoute
  '/iletisim': typeof IletisimRoute
  '/karsilastir': typeof KarsilastirRoute
  '/kosullar': typeof KosullarRoute
  '/sihirbaz': typeof SihirbazRoute
  '/hamilelik/$donem': typeof HamilelikDonemRoute
  '/isimler/$isim': typeof IsimlerIsimRoute
  '/rehber/$slug': typeof RehberSlugRoute
  '/hamilelik/': typeof HamilelikIndexRoute
  '/isimler/': typeof IsimlerIndexRoute
  '/rehber/': typeof RehberIndexRoute
  '/urunler/': typeof UrunlerIndexRoute
  '/urunler/$kategori/$slug': typeof UrunlerKategoriSlugRoute
  '/urunler/$kategori/': typeof UrunlerKategoriIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gizlilik': typeof GizlilikRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hesabim': typeof HesabimRoute
  '/iletisim': typeof IletisimRoute
  '/karsilastir': typeof KarsilastirRoute
  '/kosullar': typeof KosullarRoute
  '/sihirbaz': typeof SihirbazRoute
  '/hamilelik/$donem': typeof HamilelikDonemRoute
  '/isimler/$isim': typeof IsimlerIsimRoute
  '/rehber/$slug': typeof RehberSlugRoute
  '/hamilelik': typeof HamilelikIndexRoute
  '/isimler': typeof IsimlerIndexRoute
  '/rehber': typeof RehberIndexRoute
  '/urunler': typeof UrunlerIndexRoute
  '/urunler/$kategori/$slug': typeof UrunlerKategoriSlugRoute
  '/urunler/$kategori': typeof UrunlerKategoriIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gizlilik': typeof GizlilikRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hesabim': typeof HesabimRoute
  '/iletisim': typeof IletisimRoute
  '/karsilastir': typeof KarsilastirRoute
  '/kosullar': typeof KosullarRoute
  '/sihirbaz': typeof SihirbazRoute
  '/hamilelik/$donem': typeof HamilelikDonemRoute
  '/isimler/$isim': typeof IsimlerIsimRoute
  '/rehber/$slug': typeof RehberSlugRoute
  '/hamilelik/': typeof HamilelikIndexRoute
  '/isimler/': typeof IsimlerIndexRoute
  '/rehber/': typeof RehberIndexRoute
  '/urunler/': typeof UrunlerIndexRoute
  '/urunler/$kategori/$slug': typeof UrunlerKategoriSlugRoute
  '/urunler/$kategori/': typeof UrunlerKategoriIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gizlilik'
    | '/hakkimizda'
    | '/hesabim'
    | '/iletisim'
    | '/karsilastir'
    | '/kosullar'
    | '/sihirbaz'
    | '/hamilelik/$donem'
    | '/isimler/$isim'
    | '/rehber/$slug'
    | '/hamilelik/'
    | '/isimler/'
    | '/rehber/'
    | '/urunler/'
    | '/urunler/$kategori/$slug'
    | '/urunler/$kategori/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gizlilik'
    | '/hakkimizda'
    | '/hesabim'
    | '/iletisim'
    | '/karsilastir'
    | '/kosullar'
    | '/sihirbaz'
    | '/hamilelik/$donem'
    | '/isimler/$isim'
    | '/rehber/$slug'
    | '/hamilelik'
    | '/isimler'
    | '/rehber'
    | '/urunler'
    | '/urunler/$kategori/$slug'
    | '/urunler/$kategori'
  id:
    | '__root__'
    | '/'
    | '/gizlilik'
    | '/hakkimizda'
    | '/hesabim'
    | '/iletisim'
    | '/karsilastir'
    | '/kosullar'
    | '/sihirbaz'
    | '/hamilelik/$donem'
    | '/isimler/$isim'
    | '/rehber/$slug'
    | '/hamilelik/'
    | '/isimler/'
    | '/rehber/'
    | '/urunler/'
    | '/urunler/$kategori/$slug'
    | '/urunler/$kategori/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GizlilikRoute: typeof GizlilikRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  HesabimRoute: typeof HesabimRoute
  IletisimRoute: typeof IletisimRoute
  KarsilastirRoute: typeof KarsilastirRoute
  KosullarRoute: typeof KosullarRoute
  SihirbazRoute: typeof SihirbazRoute
  HamilelikDonemRoute: typeof HamilelikDonemRoute
  IsimlerIsimRoute: typeof IsimlerIsimRoute
  RehberSlugRoute: typeof RehberSlugRoute
  HamilelikIndexRoute: typeof HamilelikIndexRoute
  IsimlerIndexRoute: typeof IsimlerIndexRoute
  RehberIndexRoute: typeof RehberIndexRoute
  UrunlerIndexRoute: typeof UrunlerIndexRoute
  UrunlerKategoriSlugRoute: typeof UrunlerKategoriSlugRoute
  UrunlerKategoriIndexRoute: typeof UrunlerKategoriIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sihirbaz': {
      id: '/sihirbaz'
      path: '/sihirbaz'
      fullPath: '/sihirbaz'
      preLoaderRoute: typeof SihirbazRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kosullar': {
      id: '/kosullar'
      path: '/kosullar'
      fullPath: '/kosullar'
      preLoaderRoute: typeof KosullarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karsilastir': {
      id: '/karsilastir'
      path: '/karsilastir'
      fullPath: '/karsilastir'
      preLoaderRoute: typeof KarsilastirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hesabim': {
      id: '/hesabim'
      path: '/hesabim'
      fullPath: '/hesabim'
      preLoaderRoute: typeof HesabimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik': {
      id: '/gizlilik'
      path: '/gizlilik'
      fullPath: '/gizlilik'
      preLoaderRoute: typeof GizlilikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urunler/': {
      id: '/urunler/'
      path: '/urunler'
      fullPath: '/urunler/'
      preLoaderRoute: typeof UrunlerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rehber/': {
      id: '/rehber/'
      path: '/rehber'
      fullPath: '/rehber/'
      preLoaderRoute: typeof RehberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isimler/': {
      id: '/isimler/'
      path: '/isimler'
      fullPath: '/isimler/'
      preLoaderRoute: typeof IsimlerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hamilelik/': {
      id: '/hamilelik/'
      path: '/hamilelik'
      fullPath: '/hamilelik/'
      preLoaderRoute: typeof HamilelikIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rehber/$slug': {
      id: '/rehber/$slug'
      path: '/rehber/$slug'
      fullPath: '/rehber/$slug'
      preLoaderRoute: typeof RehberSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isimler/$isim': {
      id: '/isimler/$isim'
      path: '/isimler/$isim'
      fullPath: '/isimler/$isim'
      preLoaderRoute: typeof IsimlerIsimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hamilelik/$donem': {
      id: '/hamilelik/$donem'
      path: '/hamilelik/$donem'
      fullPath: '/hamilelik/$donem'
      preLoaderRoute: typeof HamilelikDonemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urunler/$kategori/': {
      id: '/urunler/$kategori/'
      path: '/urunler/$kategori'
      fullPath: '/urunler/$kategori/'
      preLoaderRoute: typeof UrunlerKategoriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urunler/$kategori/$slug': {
      id: '/urunler/$kategori/$slug'
      path: '/urunler/$kategori/$slug'
      fullPath: '/urunler/$kategori/$slug'
      preLoaderRoute: typeof UrunlerKategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GizlilikRoute: GizlilikRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  HesabimRoute: HesabimRoute,
  IletisimRoute: IletisimRoute,
  KarsilastirRoute: KarsilastirRoute,
  KosullarRoute: KosullarRoute,
  SihirbazRoute: SihirbazRoute,
  HamilelikDonemRoute: HamilelikDonemRoute,
  IsimlerIsimRoute: IsimlerIsimRoute,
  RehberSlugRoute: RehberSlugRoute,
  HamilelikIndexRoute: HamilelikIndexRoute,
  IsimlerIndexRoute: IsimlerIndexRoute,
  RehberIndexRoute: RehberIndexRoute,
  UrunlerIndexRoute: UrunlerIndexRoute,
  UrunlerKategoriSlugRoute: UrunlerKategoriSlugRoute,
  UrunlerKategoriIndexRoute: UrunlerKategoriIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
